name: Lab 3 Grading

on:
  push:
    branches: [lab03]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create KinD cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: lab3-cluster

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/

      - name: Run Grading Script
        run: |
          chmod +x ./tests/lab3_test.sh
          ./tests/lab3_test.sh